language: python
python:
  - "2.7"

before_install:
  - wget -O - http://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -qq
  - sudo apt-get install neo4j

install:
  - python setup.py -q install
  - pip install -r test_requirements.txt

before_script:
  - mysql -e 'create database test_db;'

script:
  - make test

notifications:
  email: false
  webhooks: http://finebot.herokuapp.com/hubot/travis/?room=30565_platform@conf.hipchat.com
